### PR TITLE
error gramatical en español GRAVE!!! 

### PR DESCRIPTION
**Pull request by gatomo-oficial**
Soy español y la frase "Está lo suficientemente DESCANSADO para descansar" Está mal. El correcto es "...CANSADO para descansar"
Para esto debéis contar con un español XD

Y tengo una duda, como cambio el idioma de ingles a español?

### CODE REVIEW

**Comment by gatomo-oficial** [comment]
@HelloWorld017

**Comment by HelloWorld017** [comment]
As I don't know about espanol, please write the issue in English.

**Comment by gatomo-oficial** [comment]
I am Spanish and the phrase "Está lo suficientemente DESCANSADO para descansar" (You are RESTED enough to rest) is wrong. The correct one is "...CANSADO para descansar" (... TIRED to rest)
For this you must have a Spanish *like me* XD

And I have a question, how do I change the language from English to Spanish?

ping: @HelloWorld017

**Comment by gatomo-oficial** [comment]
https://github.com/HelloWorld017/atom-discord/pull/96#issuecomment-629931362
you can use the translate, like me or all the world
https://translate.google.com

**Comment by HelloWorld017** [comment]
I think the author might try to translate a tiny joke, which original text is "The Developer is RESTful enough to rest!". But I think that is too hard to translate and just "tired to rest" is enough.

For your question, you could change it in Atom Settings > Packages > atom-discord.

**Comment by gatomo-oficial** [comment]
thanks

**Pull request merged**
